services:
  app:
    container_name: luonnonmetsakartta-service
    build: .
    env_file:
      - ./.env
    environment:
      IS_PRODUCTION: False
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - "${DEV_PORT}:80"
      - "${NOTEBOOK_PORT}:8888"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
      # - ./.conda-pkgs:/root/conda/pkgs
      - ./.vscode-server:/root/.vscode-server
      - python-dev:/root/dev
      - type: bind
        source: $HOST_SSH_AUTH_SOCK # e.g. /home/<youruser>/.ssh/agent.sock
        target: /ssh-agent
    entrypoint: [ "/bin/bash", "/app/docker-entrypoint.sh" ]
    networks:
      - luonnonmetsakartta-net

  postgis-dev:
    image: kartoza/postgis:${DEV_POSTGRES_VERSION}
    container_name: ${DEV_POSTGRES_HOST}
    hostname: ${DEV_POSTGRES_HOST}
    env_file:
      - .env
    # volumes:
    # - ${CERT_DIR}/fullchain.pem:${CERT_DIR}/fullchain.pem
    # - ${CERT_DIR}/privkey.pem:${CERT_DIR}/privkey.pem
    # - ${CERT_DIR}/server.crt:${CERT_DIR}/server.crt
    #   - /mnt/postgis-data:/var/lib/postgresql
    ports:
      - ${DEV_POSTGRES_OUT_PORT}:${DEV_POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${DEV_POSTGRES_HOST}
      POSTGRES_PORT: ${DEV_POSTGRES_PORT}

      FORCE_SSL: FALSE
    # - SSL_DIR=${CERT_DIR}
    # - SSL_CERT_FILE=${CERT_DIR}/fullchain.pem
    # - SSL_KEY_FILE=${CERT_DIR}/privkey.pem
    # - SSL_CA_FILE=${CERT_DIR}/server.crt
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    networks:
      - luonnonmetsakartta-net
    # shm_size: ${POSTGRES_CONTAINER_MEM}
    # deploy:
    #   resources:
    #     limits:
    #       memory: ${POSTGRES_CONTAINER_MEM}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgis-test:
    image: kartoza/postgis:${TEST_POSTGRES_VERSION}
    container_name: ${TEST_POSTGRES_HOST}
    hostname: ${TEST_POSTGRES_HOST}
    env_file:
      - .env
    # volumes:
    # - ${CERT_DIR}/fullchain.pem:${CERT_DIR}/fullchain.pem
    # - ${CERT_DIR}/privkey.pem:${CERT_DIR}/privkey.pem
    # - ${CERT_DIR}/server.crt:${CERT_DIR}/server.crt
    #   - /mnt/postgis-data:/var/lib/postgresql
    ports:
      - ${TEST_POSTGRES_OUT_PORT}:${TEST_POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${TEST_POSTGRES_HOST}
      POSTGRES_PORT: ${TEST_POSTGRES_PORT}

      FORCE_SSL: FALSE
    # - SSL_DIR=${CERT_DIR}
    # - SSL_CERT_FILE=${CERT_DIR}/fullchain.pem
    # - SSL_KEY_FILE=${CERT_DIR}/privkey.pem
    # - SSL_CA_FILE=${CERT_DIR}/server.crt
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    networks:
      - luonnonmetsakartta-net
    # shm_size: ${POSTGRES_CONTAINER_MEM}
    # deploy:
    #   resources:
    #     limits:
    #       memory: ${POSTGRES_CONTAINER_MEM}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  python-dev:
    driver: local

networks:
  luonnonmetsakartta-net:
    driver: bridge
    ipam:
      driver: default
      # config:
      #   - subnet: "192.168.0.0/24"
      #     gateway: "192.168.0.1"
