services:
  app:
    container_name: python-docker-quickstart
    build: .
    env_file:
      - ./.env
    ports:
      - "${PROD_PORT}:80"
    volumes:
      - .:/app:z
      - ./.cache:/root/.cache
      # - ./.conda-pkgs:/root/conda/pkgs
      - ./.vscode-server:/root/.vscode-server
      - ${GIT_SSH_KEY}:/root/.ssh/id_rsa:z
    entrypoint: [ "/bin/bash", "/app/docker-entrypoint.prod.sh" ]

# volumes:
#   poetry-cache:
