"""empty message

Revision ID: 045bbadc2e1e
Revises: 5cc151d69f58
Create Date: 2025-05-01 11:41:29.225380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045bbadc2e1e'
down_revision: Union[str, None] = '5cc151d69f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_area', sa.Column('person_responsible', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forest_area', 'person_responsible')
    # ### end Alembic commands ###
