"""add col_options to forest_layer

Revision ID: 18151c5c20b5
Revises: c593e9e01a07
Create Date: 2025-07-21 13:01:13.352299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18151c5c20b5'
down_revision: Union[str, None] = 'c593e9e01a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_layer', sa.Column('col_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('forest_layer', sa.Column('original_id', sa.Text(), nullable=True))

    placeholder_dict = {
        "indexing_strategy": "name_municipality",
        "name_col": "nimi",
        "municipality_col": "kunta",
        "area_col": "area_ha",
        "region_col": "maakunta",
        "description_col": None,
        "id_col": None,
    }
    import json
    op.execute(
        f"UPDATE forest_layer SET col_options = '{json.dumps(placeholder_dict)}'::jsonb WHERE col_options IS NULL"
    )

    op.alter_column('forest_layer', 'col_options', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forest_layer', 'original_id')
    op.drop_column('forest_layer', 'col_options')
    # ### end Alembic commands ###
