"""Add picture

Revision ID: 52e388cb0b43
Revises: d7e265d55f72
Create Date: 2025-08-05 14:50:56.511226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52e388cb0b43'
down_revision: Union[str, None] = 'd7e265d55f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('forest_area_id', sa.UUID(), nullable=False),
    sa.Column('bucket_url', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['forest_area_id'], ['forest_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('forest_area', 'pictures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_area', sa.Column('pictures', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('picture')
    # ### end Alembic commands ###
