"""empty message

Revision ID: 5cc151d69f58
Revises: 9a77f00e73ed
Create Date: 2025-04-29 13:05:39.513809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc151d69f58'
down_revision: Union[str, None] = '9a77f00e73ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_area', sa.Column('owner', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forest_area', 'owner')
    # ### end Alembic commands ###
