"""empty message

Revision ID: 8b78b9b9d849
Revises: 
Create Date: 2024-11-12 13:27:19.095689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b78b9b9d849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forest_layer',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color_code', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forest_layer')
    # ### end Alembic commands ###
