"""Fix onupdate

Revision ID: a4d9e88420ae
Revises: b2e8a8ad3bb2
Create Date: 2025-08-13 11:49:10.406194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d9e88420ae'
down_revision: Union[str, None] = 'b2e8a8ad3bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
