"""Add cascade delete

Revision ID: b2e8a8ad3bb2
Revises: 52e388cb0b43
Create Date: 2025-08-08 14:44:48.015576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e8a8ad3bb2'
down_revision: Union[str, None] = '52e388cb0b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('picture_forest_area_id_fkey', 'picture', type_='foreignkey')
    op.create_foreign_key('picture_forest_area_id_fkey', 'picture', 'forest_area', ['forest_area_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('picture_forest_area_id_fkey', 'picture', type_='foreignkey')
    op.create_foreign_key('picture_forest_area_id_fkey', 'picture', 'forest_area', ['forest_area_id'], ['id'])
    # ### end Alembic commands ###
