"""Fix original_id being in forest_layer instead of forest_area

Revision ID: d7e265d55f72
Revises: 18151c5c20b5
Create Date: 2025-07-21 14:26:51.779580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e265d55f72'
down_revision: Union[str, None] = '18151c5c20b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_area', sa.Column('original_id', sa.Text(), nullable=True))
    op.drop_column('forest_layer', 'original_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_layer', sa.Column('original_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('forest_area', 'original_id')
    # ### end Alembic commands ###
