"""empty message

Revision ID: ddc489b71091
Revises: be296d260a4e
Create Date: 2025-02-19 10:58:07.687524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc489b71091'
down_revision: Union[str, None] = 'be296d260a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forest_layer', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forest_layer', 'is_hidden')
    # ### end Alembic commands ###
