"""empty message

Revision ID: ebdd0637737e
Revises: 8b78b9b9d849
Create Date: 2024-11-12 19:05:03.289877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebdd0637737e'
down_revision: Union[str, None] = '8b78b9b9d849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forest_area',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_ts', postgresql.TIMESTAMP(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pictures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('municipality', sa.Text(), nullable=True),
    sa.Column('geometry', Geometry('POLYGON', srid=4326, spatial_index=True), nullable=True),
    sa.Column('original_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forest_area')
    # ### end Alembic commands ###
